app:
  production:  'https://app.signpath.io'
  fqa:         'https://fqa.test.signpath.io'
  iqa:         'https://iqa.test.signpath.io'
  development: 'http://localhost'
web:
  production:  'https://about.signpath.io'
  fqa:         'https://fqa.signpath.io'
  iqa:         'https://iqa.signpath.io'
  development: 'http://localhost:4000'